language: java
jdk:
  - oraclejdk8
  - oraclejdk7

android:
   components:
     - build-tools-23.0.2
     - android-23
     - extra-android-m2repository

sudo: required

before_install: chmod +x ./gradlew
install: ./gradlew assemble --stacktrace
script: ./gradlew check